# Generated by Django 6.0.3 on 2026-03-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('official_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_user_generated', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fish_species_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('official_url', models.URLField(blank=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='main_app.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('official_url', models.URLField(blank=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='main_app.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('official_url', models.URLField(blank=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='main_app.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('official_url', models.URLField(blank=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='main_app.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('official_url', models.URLField(blank=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='main_app.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FishingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('air_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('water_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('kg', 'kg')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fishing_logs/photos/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_logs', to=settings.AUTH_USER_MODEL)),
                ('fish_species', models.ManyToManyField(related_name='fishing_logs', to='main_app.fishspecies')),
                ('hook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.hook')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.line')),
                ('lure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.lure')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.reel')),
                ('rod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.rod')),
            ],
            options={
                'ordering': ['-date', '-time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rod', 'ロッド'), ('reel', 'リール'), ('line', 'ライン'), ('hook', '針'), ('lure', 'ルアー')], max_length=10)),
                ('list_url', models.URLField()),
                ('parser', models.CharField(choices=[('generic_links', '汎用リンク抽出')], default='generic_links', max_length=30)),
                ('frequency', models.CharField(choices=[('hourly', '毎時'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月')], default='weekly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_sources', to='main_app.manufacturer')),
            ],
        ),
        migrations.AddIndex(
            model_name='fishspecies',
            index=models.Index(fields=['name'], name='main_app_fi_name_cab3d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fishspecies',
            unique_together={('name', 'is_user_generated')},
        ),
        migrations.AddIndex(
            model_name='lure',
            index=models.Index(fields=['name'], name='main_app_lu_name_311605_idx'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['name'], name='main_app_li_name_751af9_idx'),
        ),
        migrations.AddIndex(
            model_name='hook',
            index=models.Index(fields=['name'], name='main_app_ho_name_3b6d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['name'], name='main_app_re_name_933752_idx'),
        ),
        migrations.AddIndex(
            model_name='rod',
            index=models.Index(fields=['name'], name='main_app_ro_name_c46333_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapesource',
            unique_together={('manufacturer', 'category', 'list_url')},
        ),
    ]
