# Generated by Django 6.0.3 on 2026-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapesource',
            name='link_allow_pattern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapesource',
            name='link_deny_pattern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapesource',
            name='link_selector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='list_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='parser',
            field=models.CharField(choices=[('generic_links', '汎用リンク抽出'), ('sitemap', 'サイトマップ')], default='generic_links', max_length=30),
        ),
    ]
